# tools/bundle.py
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT  = ROOT / "dist" / "joinquant_strategy.py"
OUT.parent.mkdir(exist_ok=True)

# 你手动控制顺序：utils 最先，依赖它的在后
MODULES = [
    ROOT / "lib" / "utils.py",
    ROOT / "lib" / "data.py",
    ROOT / "lib" / "signal.py",
    ROOT / "lib" / "risk.py",
]

MAIN = ROOT / "strategy" / "main.py"

def strip_encoding_and_main_guard(s: str) -> str:
    # 去掉编码行、可选去掉 if __name__ == '__main__' 段
    lines = s.splitlines()
    lines = [ln for ln in lines if not ln.startswith("# -*- coding:")]
    return "\n".join(lines).strip() + "\n"

parts = []
parts.append("# === AUTO-GENERATED FILE: paste into JoinQuant strategy editor ===\n")
parts.append("# Generated by tools/bundle.py\n\n")

for p in MODULES:
    code = strip_encoding_and_main_guard(p.read_text(encoding="utf-8"))
    parts.append(f"\n# ===== BEGIN {p.relative_to(ROOT)} =====\n")
    parts.append(code)
    parts.append(f"# ===== END {p.relative_to(ROOT)} =====\n")

main_code = strip_encoding_and_main_guard(MAIN.read_text(encoding="utf-8"))
# 关键：main.py 里不要再写 from lib.xxx import ...，而是直接用上面内联的函数/类名
parts.append("\n# ===== BEGIN strategy/main.py =====\n")
parts.append(main_code)
parts.append("# ===== END strategy/main.py =====\n")

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Written: {OUT}")
